# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-22T23:28:51+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, RootModel, conint, constr


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=1, max_length=200)
    company: constr(min_length=1, max_length=200)
    salary_min: conint(ge=0, le=9007199254740991)
    salary_max: conint(ge=0, le=9007199254740991)


class Atom(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(pattern=r'^pk_atom_[A-Z0-9]{26}$')
    object: Literal['atom']
    created_at: str
    metadata: dict[str, Any]
    data: Data


class Job(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    title: constr(min_length=1, max_length=200)
    company: constr(min_length=1, max_length=200)
    salary_min: conint(ge=0, le=9007199254740991)
    salary_max: conint(ge=0, le=9007199254740991)


class Model(RootModel[Atom]):
    root: Atom
