# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-05-23T06:20:16+00:00

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, RootModel, conint


class Payload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    value: str


class WireFrame1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['data']
    payload: Payload


class WireFrame2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['error']
    code: str
    message: str


class WireFrame3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['progress']
    percent: conint(ge=0, le=100)


class WireFrame(RootModel[WireFrame1 | WireFrame2 | WireFrame3]):
    root: WireFrame1 | WireFrame2 | WireFrame3


class Model(RootModel[WireFrame]):
    root: WireFrame
