/**
 * Unit tests for `datamodel-codegen.ts`.
 *
 * Uses vi.mock to intercept `child_process.execFile` — no uv required.
 * Tests the subprocess wrapper contract: success / failure paths,
 * stdout-capture mode (`outputPath === '-'`), and temp-file cleanup.
 */

import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// ---------------------------------------------------------------------------
// Mock child_process.execFile before importing the module under test.
// The module uses `promisify(execFile)` at module load time, so we need the
// mock in place before the import resolves.
// ---------------------------------------------------------------------------

vi.mock('node:child_process', async (importOriginal) => {
  const actual = await importOriginal<typeof import('node:child_process')>();
  return {
    ...actual,
    execFile: vi.fn(),
  };
});

import { execFile } from 'node:child_process';
import { runDatamodelCodegen } from '../src/lib/datamodel-codegen.js';

// Typed reference to the mock
const mockExecFile = execFile as unknown as ReturnType<typeof vi.fn>;

// ---------------------------------------------------------------------------
// Test helpers
// ---------------------------------------------------------------------------

const SIMPLE_SCHEMA_JSON = JSON.stringify({
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  type: 'object',
  properties: { name: { type: 'string' } },
});

const FAKE_PY_OUTPUT = `# generated by datamodel-codegen
from pydantic import BaseModel

class MyModel(BaseModel):
    name: str
`;

// ---------------------------------------------------------------------------
// Setup — wire mock to call callback with specified args
// ---------------------------------------------------------------------------

type ExecFileCallback = (err: Error | null, stdout: string, stderr: string) => void;

beforeEach(() => {
  vi.clearAllMocks();
});

afterEach(() => {
  vi.clearAllMocks();
});

// ---------------------------------------------------------------------------
// Success path — write to file
// ---------------------------------------------------------------------------

describe('runDatamodelCodegen — success (file output)', () => {
  it('passes "uv" as the command and includes expected argv elements', async () => {
    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        // Write the output file so readFile works in stdout mode
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, '', 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    await runDatamodelCodegen({ schemaJson: SIMPLE_SCHEMA_JSON, outputPath: '-' });

    expect(mockExecFile).toHaveBeenCalledOnce();
    const [cmd, args] = mockExecFile.mock.calls[0] as [string, string[]];
    expect(cmd).toBe('uv');
    expect(args).toContain('datamodel-codegen');
    expect(args).toContain('jsonschema');
    expect(args).toContain('pydantic_v2.BaseModel');
  });

  it('includes --input-file-type jsonschema in argv', async () => {
    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, '', 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    await runDatamodelCodegen({ schemaJson: SIMPLE_SCHEMA_JSON, outputPath: '-' });

    const [, args] = mockExecFile.mock.calls[0] as [string, string[]];
    const inputFileTypeIdx = args.indexOf('--input-file-type');
    expect(inputFileTypeIdx).toBeGreaterThanOrEqual(0);
    expect(args[inputFileTypeIdx + 1]).toBe('jsonschema');
  });

  it('returns success:true when execFile succeeds', async () => {
    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, FAKE_PY_OUTPUT, 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    const result = await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '-',
    });

    expect(result.success).toBe(true);
    // stderr is a string (possibly empty) on success
    expect(typeof (result.stderr ?? '')).toBe('string');
  });

  it('call is made with a valid callback signature', async () => {
    // Verify that execFile is called with (cmd, args, opts, callback) — 4 arguments
    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, '', 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '-',
    });

    expect(mockExecFile).toHaveBeenCalledOnce();
    const callArgs = mockExecFile.mock.calls[0] as unknown[];
    // (cmd, args, opts, callback)
    expect(callArgs).toHaveLength(4);
    expect(typeof callArgs[3]).toBe('function');
  });
});

// ---------------------------------------------------------------------------
// Failure path
// ---------------------------------------------------------------------------

describe('runDatamodelCodegen — failure', () => {
  it('returns success:false when execFile fails with .stderr property', async () => {
    mockExecFile.mockImplementation(
      (_cmd: string, _args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const err = Object.assign(new Error('codegen error'), {
          stderr: 'some codegen error on stderr',
        });
        setImmediate(() => cb(err, '', 'some codegen error on stderr'));
      },
    );

    const result = await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '/tmp/out.py',
    });

    expect(result.success).toBe(false);
    expect(result.stderr).toMatch(/codegen error|some codegen error/);
  });

  it('returns success:false with message when error has no .stderr', async () => {
    mockExecFile.mockImplementation(
      (_cmd: string, _args: string[], _opts: unknown, cb: ExecFileCallback) => {
        setImmediate(() => cb(new Error('unexpected failure'), '', ''));
      },
    );

    const result = await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '/tmp/out.py',
    });

    expect(result.success).toBe(false);
    expect(result.stderr).toMatch(/unexpected failure/);
  });
});

// ---------------------------------------------------------------------------
// stdout capture mode (outputPath === '-')
// ---------------------------------------------------------------------------

describe('runDatamodelCodegen — stdout mode (outputPath === "-")', () => {
  it('reads back the temp file and returns it as output', async () => {
    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, FAKE_PY_OUTPUT, 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    const result = await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '-',
    });

    expect(result.success).toBe(true);
    expect(result.output).toBe(FAKE_PY_OUTPUT);
  });

  it('in stdout mode, output contains the generated content', async () => {
    const content = '# generated\nfrom pydantic import BaseModel\nclass M(BaseModel): pass\n';

    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, content, 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    const result = await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '-',
    });

    expect(result.success).toBe(true);
    expect(result.output).toContain('BaseModel');
  });
});

// ---------------------------------------------------------------------------
// Temp dir cleanup
// ---------------------------------------------------------------------------

describe('runDatamodelCodegen — temp dir cleanup', () => {
  it('temp directory is removed after a successful run', async () => {
    let capturedTmpDir: string | undefined;

    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const inputIdx = args.indexOf('--input');
        const inputPath = args[inputIdx + 1];
        if (inputPath) {
          capturedTmpDir = inputPath.replace(/\/schema\.json$/, '');
        }
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, '', 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '-',
    });

    if (capturedTmpDir) {
      expect(existsSync(capturedTmpDir)).toBe(false);
    }
  });

  it('temp directory is removed after a failed run', async () => {
    let capturedTmpDir: string | undefined;

    mockExecFile.mockImplementation(
      (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const inputIdx = args.indexOf('--input');
        const inputPath = args[inputIdx + 1];
        if (inputPath) capturedTmpDir = inputPath.replace(/\/schema\.json$/, '');
        const err = Object.assign(new Error('fail'), { stderr: 'fail' });
        setImmediate(() => cb(err, '', 'fail'));
      },
    );

    await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '-',
    });

    if (capturedTmpDir) {
      expect(existsSync(capturedTmpDir)).toBe(false);
    }
  });
});

// ---------------------------------------------------------------------------
// Schema file content written to temp dir
// ---------------------------------------------------------------------------

describe('runDatamodelCodegen — schema file content', () => {
  it('writes the provided schemaJson to the temp schema.json file', async () => {
    let capturedSchemaContent: string | undefined;

    mockExecFile.mockImplementation(
      async (_cmd: string, args: string[], _opts: unknown, cb: ExecFileCallback) => {
        const inputIdx = args.indexOf('--input');
        const inputPath = args[inputIdx + 1];
        if (inputPath) {
          capturedSchemaContent = await readFile(inputPath, 'utf8');
        }
        const outIdx = args.indexOf('--output');
        const outPath = args[outIdx + 1];
        if (outPath) await writeFile(outPath, '', 'utf8');
        setImmediate(() => cb(null, '', ''));
      },
    );

    await runDatamodelCodegen({
      schemaJson: SIMPLE_SCHEMA_JSON,
      outputPath: '-',
    });

    expect(capturedSchemaContent).toBe(SIMPLE_SCHEMA_JSON);
  });
});
